language: python
sudo: false
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
install:
    - pip install --upgrade pip setuptools wheel
    - pip install --quiet --upgrade -r requirements.txt
script:
    - inv test
    - inv build
    - inv test-install
    - inv coverage
after_success:
    - coveralls
notifications:
    email: false
